### ISSUE TITLE
Query String bigger than 4000 characters result in java.lang.UnsupportedOperationException 

### ISSUE THREAD

**Issue by gslulu** [r2dbc/r2dbc-mssql#140]
## Bug Report
Sample code used to produce an error:

```
        Mono<MssqlConnection> connectionMono = dbConnectionService.getConnectionFactory().create();
        final Mono<MyRecord> myRecordMono = connectionMono.flatMap(mssqlConnection ->
                mssqlConnection.beginTransaction().then(
                        buildStatement(mssqlConnection, parm1, param2).execute().
                                flatMap(mssqlResult -> mssqlResult.map((row, rowMetadata) ->
                                        buildMyRecord(row))).switchIfEmpty(Mono.just(new MyRecord())).single()).
                        doOnError(throwable -> mssqlConnection.rollbackTransaction()).
                        doOnSuccess(r -> mssqlConnection.commitTransaction()));
```

When Query String bigger than 4000 characters result in 
```
java.lang.UnsupportedOperationException 
java.lang.UnsupportedOperationException: Use ClobCodec
	at io.r2dbc.mssql.codec.CharacterEncoder.encodeBigVarchar(CharacterEncoder.java:97) ~[r2dbc-mssql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at io.r2dbc.mssql.codec.RpcEncoding.encodeString(RpcEncoding.java:57) ~[r2dbc-mssql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at io.r2dbc.mssql.message.token.RpcRequest$RpcString.encode(RpcRequest.java:669) ~[r2dbc-mssql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at io.r2dbc.mssql.message.token.RpcRequest.lambda$encode$6(RpcRequest.java:200) ~[r2dbc-mssql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:46) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8143) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.netty.channel.MonoSendMany.subscribe(MonoSendMany.java:82) ~[reactor-netty-0.9.2.RELEASE.jar:0.9.2.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4105) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.netty.NettyOutbound.subscribe(NettyOutbound.java:329) ~[reactor-netty-0.9.2.RELEASE.jar:0.9.2.RELEASE]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:441) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:243) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:426) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.EmitterProcessor.onNext(EmitterProcessor.java:268) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.FluxCreate$IgnoreSink.next(FluxCreate.java:618) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at io.r2dbc.mssql.client.ReactorNettyClient.lambda$null$11(ReactorNettyClient.java:525) ~[r2dbc-mssql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1630) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.MonoSupplier.subscribe(MonoSupplier.java:61) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8143) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.Flux.subscribeWith(Flux.java:8307) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8114) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8041) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at io.r2dbc.mssql.client.ReactorNettyClient.lambda$null$13(ReactorNettyClient.java:518) ~[r2dbc-mssql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onSubscribe(FluxPeek.java:154) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.EmitterProcessor.subscribe(EmitterProcessor.java:169) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8143) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:188) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at io.r2dbc.mssql.client.ReactorNettyClient$ExchangeRequest$1.onSuccess(ReactorNettyClient.java:701) ~[r2dbc-mssql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at io.r2dbc.mssql.client.ReactorNettyClient$RequestQueue.run(ReactorNettyClient.java:614) ~[r2dbc-mssql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onComplete(FluxPeekFuseable.java:936) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.FluxHandle$HandleConditionalSubscriber.onNext(FluxHandle.java:335) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:426) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.EmitterProcessor.onNext(EmitterProcessor.java:268) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at io.r2dbc.mssql.client.ReactorNettyClient$1.next(ReactorNettyClient.java:231) ~[r2dbc-mssql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at io.r2dbc.mssql.client.ReactorNettyClient$1.next(ReactorNettyClient.java:191) ~[r2dbc-mssql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at io.r2dbc.mssql.message.token.Tabular$TabularDecoder.decode(Tabular.java:425) ~[r2dbc-mssql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at io.r2dbc.mssql.client.ConnectionState$4$1.decode(ConnectionState.java:206) ~[r2dbc-mssql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at io.r2dbc.mssql.client.StreamDecoder.withState(StreamDecoder.java:137) ~[r2dbc-mssql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at io.r2dbc.mssql.client.StreamDecoder.decode(StreamDecoder.java:109) ~[r2dbc-mssql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at io.r2dbc.mssql.client.ReactorNettyClient.lambda$new$6(ReactorNettyClient.java:241) ~[r2dbc-mssql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:177) ~[reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:218) ~[reactor-netty-0.9.2.RELEASE.jar:0.9.2.RELEASE]
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:351) ~[reactor-netty-0.9.2.RELEASE.jar:0.9.2.RELEASE]
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:348) ~[reactor-netty-0.9.2.RELEASE.jar:0.9.2.RELEASE]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:89) ~[reactor-netty-0.9.2.RELEASE.jar:0.9.2.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.r2dbc.mssql.client.ssl.TdsSslHandler.channelRead(TdsSslHandler.java:402) ~[r2dbc-mssql-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[netty-transport-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.43.Final.jar:4.1.43.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

#### Versions

- Driver: io.r2dbc:r2dbc-mssql:0.8.1.RELEASE / 0.8.0.RELEASE
- Database: SQL Server 
- Java: 11
- OS: Windows

#### Current Behavior

<details>
<summary>Stack trace</summary>

```
// your stack trace here
```

</details>
 
#### Table schema

<details>
<summary>Input Code</summary>

```sql
-- your SQL here;
```

</details>

#### Steps to reproduce

<details>
<summary>Input Code</summary>

```java
// your code here;
```

</details>

**Comment by mp911de** [comment]
We need to check how the JDBC driver behaves in that case. IIRC, the RPC query parameter for the query must be a `(N)VARCHAR` type.

**Comment by gslulu** [comment]
> We need to check how the JDBC driver behaves in that case. IIRC, the RPC query parameter for the query must be a `(N)VARCHAR` type.

The issue is not with the parameter being long. All the parameters in my testing are less than 15 characters. 
The error is thrown for when the query string itself is more than 4000 characters

**Comment by mp911de** [comment]
Indeed, that's how I understood the issue. By default, queries are sent via RPC (`sp_prepexec`, `sp_cursoropen`, …). The actual query is sent as well as a parameter.

**Comment by gslulu** [comment]
I see. Sorry, for the confusion on that.
I was hoping that the configuration of sendStringParametersAsUnicode as false would allow me 8000 single-byte characters, but the code [here](https://github.com/r2dbc/r2dbc-mssql/blob/4334af77e2146fc34dca0b0e505a9533b1f486c5/src/main/java/io/r2dbc/mssql/codec/CharacterEncoder.java#L74) hard codes the value to true.

**Comment by gslulu** [comment]
ok, sorry for the confusion. 
I see a lot of online discussion around this 4000 character limit for queries with other Ms SQL drivers too. 

Is there a way to tweak the MssqlStatement or the MssqlConnection to make them treat the query string as a single-byte character set instead of unicode, that way the cap is 8000 instead of 4000.

I tried MssqlConnectionConfiguration.sendStringParametersAsUnicode set as 'false', but it made no difference

**Comment by mp911de** [comment]
Have you checked what the Microsoft JDBC driver does and how it behaves in such a case? It would make sense to align with mssql-jdbc in that regard.

**Comment by gslulu** [comment]
Ok, I agree. Let me check the MS JDBC behavior, will post the update.

**Comment by gslulu** [comment]
The MS JDBC Driver works fine:

Here is an example code I tried:

   @GetMapping("/test")
    public void test() throws SQLException {
        final PreparedStatement preparedStatement = dataSource.getConnection().prepareStatement(getQuery());
        preparedStatement.execute();
        preparedStatement.getResultSet().next();
        System.out.println(preparedStatement.getResultSet() .getDate("A"));
    }

    private String getQuery() {
        StringBuffer stringBuffer = new StringBuffer("select ");
        IntStream.range(1, 4000).
                forEach(value -> stringBuffer.append("sysdatetime(),"));
        stringBuffer.append("sysdatetime() A");
        System.out.println("Length of String: " + stringBuffer.toString().length());
        return stringBuffer.toString();
    }
}


The output was:
Length of String: 56008
2020-02-20

I used: 
org.springframework.boot.spring-boot-starter-data-jdbc:2.2.4.RELEASE & 
com.microsoft.sqlserver.mssql-jdbc:7.4.1.jre8

**Comment by mp911de** [comment]
Thanks for trying this out. The JDBC driver sends large queries as chunked values (PLP). We can do the same for R2DBC MSSQL.

**Comment by gslulu** [comment]
That was very quick.
When will the 0.8.2.RELEASE be available?

Is there a version tag that has the fixed code baked in so I can try now?

**Comment by mp911de** [comment]
We have for now snapshots only. I expect a service release end of March.

**Comment by gslulu** [comment]
Ok... Thank You so much Mark. I'll use the snapshot and test it out. Will update here if I notice any issue.
