### ISSUE TITLE
Add EnumCodec

### ISSUE THREAD

**Issue by stdreyer** [r2dbc/r2dbc-mssql#33]
When trying to save an object that contains an `enum` value, I got the following error:

```
java.lang.IllegalArgumentException: Cannot encode [MY_VALUE] parameter of type [com.mycompany.MyEnum]
	at io.r2dbc.mssql.codec.DefaultCodecs.encode(DefaultCodecs.java:92) ~[r2dbc-mssql-1.0.0.M7.jar:1.0.0.M7]
	at io.r2dbc.mssql.PreparedMssqlStatement.bind(PreparedMssqlStatement.java:155) ~[r2dbc-mssql-1.0.0.M7.jar:1.0.0.M7]
	at io.r2dbc.mssql.PreparedMssqlStatement.bind(PreparedMssqlStatement.java:57) ~[r2dbc-mssql-1.0.0.M7.jar:1.0.0.M7]
	at org.springframework.data.r2dbc.dialect.NamedBindMarkers$NamedBindMarker.bind(NamedBindMarkers.java:105) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.data.r2dbc.function.DefaultReactiveDataAccessStrategy$DefaultBindableInsert.bind(DefaultReactiveDataAccessStrategy.java:465) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.data.r2dbc.function.BindableOperation.bind(BindableOperation.java:53) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.data.r2dbc.function.DefaultDatabaseClient$DefaultTypedInsertSpec.lambda$exchange$2(DefaultDatabaseClient.java:996) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.data.r2dbc.function.DefaultDatabaseClient$DefaultTypedInsertSpec.lambda$exchange$3(DefaultDatabaseClient.java:1002) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.data.r2dbc.function.DefaultSqlResult$2.apply(DefaultSqlResult.java:81) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.data.r2dbc.function.DefaultSqlResult$2.apply(DefaultSqlResult.java:78) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.data.r2dbc.function.DefaultDatabaseClient.doInConnectionMany(DefaultDatabaseClient.java:1018) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
	at org.springframework.data.r2dbc.function.DefaultDatabaseClient.lambda$inConnectionMany$2(DefaultDatabaseClient.java:159) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
```

There is no EnumCodec yet, but once implemented it should look like the one from postgresql: https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/codec/EnumCodec.java

Interestingly decoding of `varchar` to an `enum` value works. It is decoded to a `String` and Springs `ConversionService` turns it into an `enum` value.

I would have added a codec by myself, but there is no easy way to add a custom codec to `DefaultCodecs`.

**Comment by mp911de** [comment]
Thanks for your suggestion. I think it makes sense to add enum support here so we get a sense of consistency. Serializing enums is a double-edged sword: You can represent it either as character data using the name or its ordinal where the latter one is less-compatible.

Can you please file an issue in R2DBC SPI to ask for a specification of enum serialization so we can at least specify how drivers *should* handle enum values.

Do you also want to submit a pull request for enum support? Feel free to get some inspiration from the `String` codec and/or reuse existing codecs.

**Comment by gregturn** [comment]
Is this an SPI issue or an issue for clients to decide how to convert between enums and the target column type?

**Comment by mp911de** [comment]
Primarily it is a client issue. However, it could make sense to add a note (suggestion?) to our specification (see https://github.com/r2dbc/r2dbc-spi/pull/51/files#diff-46abe2dfa890d75dfe2188cb02cc6d77R10) to mention how we suggest that drivers could handle enum values.

**Comment by essentinal** [comment]
I've added a EnumCodec for now. This provides the feature the same way other implementations (like PostgreSQL) did. There may also be a way to solve it in a general way, but that's too much effort for me now.
About the ordinal/character representation: JPA does it using annotations like `@Enumerated(EnumType.STRING)`.

**Comment by mp911de** [comment]
Thanks a lot.

**Comment by gregturn** [comment]
See discussion on #34.

**Comment by mp911de** [comment]
Closing as per discussion in #34.
