### ISSUE TITLE
NotSslRecordException thrown when connecting to Azure SQL Server

### ISSUE THREAD

**Issue by Ih8Cocoa** [r2dbc/r2dbc-mssql#77]
When I try to connect to Azure SQL Server using R2DBC and execute a query, it throws this exception
```
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: afcbfe5c0e000000
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472) ~[netty-codec-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-codec-4.1.36.Final.jar:4.1.36.Final]
	at io.r2dbc.mssql.client.ssl.TdsSslHandler.channelRead(TdsSslHandler.java:359) ~[r2dbc-mssql-1.0.0.M7.jar:1.0.0.M7]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.36.Final.jar:4.1.36.Final]
	at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.FluxConcatMap] :
	reactor.core.publisher.Flux.concatMap(Flux.java:3446)
	io.r2dbc.mssql.client.ReactorNettyClient.<init>(ReactorNettyClient.java:171)
Error has been observed at the following site(s):
	|_ Flux.concatMap ⇢ at io.r2dbc.mssql.client.ReactorNettyClient.<init>(ReactorNettyClient.java:171)
	|_  Flux.doOnNext ⇢ at io.r2dbc.mssql.client.ReactorNettyClient.<init>(ReactorNettyClient.java:186)
```
This occurs both with and without using `MssqlConnectionConfiguration.Builder.enableSsl()` on the configuration method

**Libraries used**: `r2dbc-mssql 1.0.0.M7` and `spring-data-r2dbc 1.0.0.M2`
**JDK version**: Oracle JDK 12 running on Windows 10

**Comment by mp911de** [comment]
I wasn't able to reproduce the issue with an Azure SQL database using Gen4 and dedicated hosting.
How can I reproduce the issue?

**Comment by Ih8Cocoa** [comment]
The following configuration worked fine
``` kotlin
@Configuration
@Profile("works-fine")
@EnableR2dbcRepositories
class ConfigOne : AbstractR2dbcConfiguration() {
    override fun connectionFactory(): ConnectionFactory {
        val config = MssqlConnectionConfiguration.builder()
                .host("abcazuretestdb.database.windows.net")
                .database("test")
                .username("abcuser")
                .password("Upp3rcase")
                .enableSsl().build()
        return MssqlConnectionFactory(config)
    }
}
```
But the following configuration throws the described exception, even when I deleted the database and recreate a new one from scratch
``` kotlin
@Configuration
@Profile("doesnt-work")
@EnableR2dbcRepositories
class DbConfig : AbstractR2dbcConfiguration() {
    override fun connectionFactory(): ConnectionFactory {
        val config = MssqlConnectionConfiguration.builder()
                .host("abcbookstore.database.windows.net")
                .database("AbcBookStoreDb")
                .username("meow")
                .password("M30wm30wm30w")
                .enableSsl().build()
        return MssqlConnectionFactory(config)
    }
}
```

**Comment by Ih8Cocoa** [comment]
I'm closing this issue since it seems to worked fine now, when I deleted the database and recreated it from scratch

**Comment by mp911de** [comment]
This is indeed strange. Let me know if you have something that is able to reproduce the issue.

**Comment by Ih8Cocoa** [comment]
Sorry, it didn't work again
This config can successfully connect to the database
``` kotlin
@Configuration
@Profile("works-fine")
@EnableR2dbcRepositories
class ConfigOne : AbstractR2dbcConfiguration() {
    override fun connectionFactory(): ConnectionFactory {
        val config = MssqlConnectionConfiguration.builder()
                .host("abcazuretestdb.database.windows.net")
                .database("test")
                .username("abcuser")
                .password("Upp3rcase")
                .enableSsl().build()
        return MssqlConnectionFactory(config)
    }
}
```
But this config causes the mentioned exception to occur
``` kotlin
@Configuration
@Profile("doesnt-work")
@EnableR2dbcRepositories
class DbConfig : AbstractR2dbcConfiguration() {
    override fun connectionFactory(): ConnectionFactory {
        val config = MssqlConnectionConfiguration.builder()
                .host("abcbookstore.database.windows.net")
                .database("AbcBookStoreDb")
                .username("meow")
                .password("M30wm30wm30w")
                .enableSsl().build()
        return MssqlConnectionFactory(config)
    }
}
```

**Comment by Ih8Cocoa** [comment]
Here is the rest of the code just in case: [https://github.com/Ih8Cocoa/demo](repo)

**Comment by Ih8Cocoa** [comment]
It seems that switching to JDK 8 solved this issue

**Comment by mp911de** [comment]
The issue seems related to the used protocol version. Using TLS 1.1 works while TLS 1.2 and 1.3 fail.

**Comment by MiguelAraCo** [comment]
I'm facing the same issue but in my case changing the JDK version doesn't seem to make any difference. The solution was working one day and then 3 days later it started throwing the exception.

**Comment by Ih8Cocoa** [comment]
> I'm facing the same issue but in my case changing the JDK version doesn't seem to make any difference. The solution was working one day and then 3 days later it started throwing the exception.

Are you using Oracle JDK or OpenJDK? Oracle JDK 8 solved the issue for me.

**Comment by mp911de** [comment]
@MiguelAraCo @Ih8Cocoa Care to involve the Microsoft Azure team? Perhaps they can chime in and we can solve the issue together.

**Comment by MiguelAraCo** [comment]
@Ih8Cocoa Thank you for the advice. I won't be able to try it for the time being as I went back to non-reactive jdbc due to this issue (have to meet a deadline 😓 ). I didn't try with Oracle JDK but I did try with Amazon's and OpenJDK without any luck.

**Comment by arunim29** [comment]
Hi, I am facing the issue even when using JDK 8. I raised a ticket with microsoft regarding this. So, they asked for the network traces. I sent them two network traces.

![image](https://user-images.githubusercontent.com/53040069/61445270-b3d1a800-a96a-11e9-8991-425c7781130e.png)

This trace was captured when using JDBC for connecting to azure SQL db.

The analysis is -:
This three messages are showing that the connection was well done:

Client Hello -> The client machine sends a message to the SQL Server
Handshake -> 10 frames later, the Client machine trade cipher suites using TLS 1.2
Change Cipher Spec -> Server replies with ChangeCipherSpec confirming that the TCP connection succeeded.

![image](https://user-images.githubusercontent.com/53040069/61445289-bdf3a680-a96a-11e9-9eb9-0120c5fe5f9f.png)


This trace was captured when using R2DBC for connecting to azure SQL db.
Now looking for the highlighted frames:

Client Hello -> Ok. This can be found
Handshake -> This is missing. The client machine is not sending its handshake TLS specifications.
Change Cipher Spec -> This is still missing, because the handshake was not sent by the client.

So, the server is responding in the same way in both JDBC and R2DBC, but the R2DBC library is not able to understand the server.

If you need anything more, let me know.

**Comment by mp911de** [comment]
Yeah, this is what we see also on the client side. The driver sends a request for handshake and the server responds with a packet of which the last 8 bytes are not understood and then the SSL handshake fails.

**Comment by arunim29** [comment]
So, should there be a change in library then?

**Comment by arunim29** [comment]
I am using JDK 8 and still I am facing this issue.

**Comment by mp911de** [comment]
Make sure to use the latest snapshot: https://repo.spring.io/snapshot/io/r2dbc/r2dbc-mssql/0.8.0.BUILD-SNAPSHOT/r2dbc-mssql-0.8.0.BUILD-20190718.135719-23.jar

**Comment by arunim29** [comment]
With this jar, I am able to query the db without enableSsl() flag. When will this jar be pushed to maven repo?

**Comment by mp911de** [comment]
The next step will be a milestone or release candidate. We will ship R2DBC to Maven Central once it qualifies for a GA release.

Thanks for verifying.
