### ISSUE TITLE
IllegalArgumentException Invalid TDS type is 0 on SQL Server 2014

### ISSUE THREAD

**Issue by Technus** [r2dbc/r2dbc-mssql#90]
I am requesting only 4 columns, the data after them is unreadable?

INT4 (INTN of len4 / INT4) NVARCHAR NVARCHAR

Similar issue happens on every query i make

### Running 

- Microsoft SQL Server 2014 (SP1-CU4) (KB3106660) - 12.0.4436.0 (X64) \n	Dec  2 2015 16:09:44 \n	Copyright (c) Microsoft Corporation\n	Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)\n
- 0.8.0.M8 R2DBC-mssql

### Reader Dump:

- from breakpoints while reading:

raderIndex
readTDSType Type Name

```
9
56 INT4
21
38 INTN len4
46
231 NVARCHAR
69
231 NVARCHAR
112
56 INT4
219
0 null
```

- on exeception buffer rewind:

buffer.resetReaderIndex() then reading 
    [ readerIndex, (Decode.uByte(buffer),  readerIndex, (Decode.uByte(buffer), ....]

[175, 15, 176, 0, 177, 1, 178, 1, 179, 0, 180, 2, 181, 1, 182, 0, 183, 3, 184, 1, 185, 0, 186, 4, 187, 1, 188, 0, 189, 5, 190, 0, 191, 20, 192, 255, 193, 17, 194, 0, 195, 193, 196, 0, 197, 0, 198, 0, 199, 0, 200, 0, 201, 0, 202, 0, 203, 0, 204, 0, 205, 121, 206, 0, 207, 0, 208, 0, 209, 0, 210, 172, 211, 0, 212, 0, 213, 0, 214, 1, 215, 0, 216, 0, 217, 0, 218, 0, **219, 0,** 220, 0, 221, 38, 222, 4, 223, 4, 224, 243, 225, 222, 226, 188, 227, 10, 228, 172, 229, 4, 230, 0, 231, 0, 232, 1, 233, 0, 234, 0, 235, 0, 236, 0, 237, 0, 238, 0, 239, 38, 240, 4, 241, 4, 242, 255, 243, 255, 244, 255, 245, 255, 246, 254, 247, 0, 248, 0, 249, 224, 250, 0, 251, 0, 252, 0, 253, 0, 254, 0, 255, 0, 256, 0, 257, 0, 258, 0, 259]

**Comment by Technus** [comment]
```
java.lang.IllegalArgumentException: Invalid TDS type: 0
	at io.r2dbc.mssql.message.type.TdsDataType.valueOf(TdsDataType.java:107)
	at io.r2dbc.mssql.message.type.TypeBuilder.canDecode(TypeBuilder.java:446)
	at io.r2dbc.mssql.message.type.TypeInformation.canDecode(TypeInformation.java:54)
	at io.r2dbc.mssql.message.token.ReturnValue.canDecode(ReturnValue.java:135)
	at io.r2dbc.mssql.message.token.Tabular.lambda$decodeFunction$0(Tabular.java:207)
	at io.r2dbc.mssql.message.token.Tabular$TabularDecoder.decode(Tabular.java:372)
	at io.r2dbc.mssql.client.ConnectionState$4.lambda$decoder$1(ConnectionState.java:194)
	at io.r2dbc.mssql.client.StreamDecoder.lambda$decode$1(StreamDecoder.java:93)
	at reactor.core.publisher.FluxGenerate$GenerateSubscription.poll(FluxGenerate.java:347)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainSync(FluxFlattenIterable.java:498)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:635)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.request(FluxFlattenIterable.java:266)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1934)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1808)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onSubscribe(FluxFlattenIterable.java:208)
	at reactor.core.publisher.FluxGenerate.subscribe(FluxGenerate.java:83)
	at reactor.core.publisher.FluxFlattenIterable.subscribe(FluxFlattenIterable.java:109)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7800)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:442)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:244)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:206)
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:322)
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:335)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:91)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1478)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1227)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.r2dbc.mssql.client.ssl.TdsSslHandler.channelRead(TdsSslHandler.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by Technus** [comment]
Hex dump of the packet:

0000   54 e1 ad 44 39 a1 c4 64 13 e3 8e c3 08 00 45 00   T..D9..d......E.
0010   01 33 19 46 40 00 7b 06 6f 59 0a 64 19 33 0a 6c   .3.F@.{.oY.d.3.l
0020   48 23 05 99 d7 7d 59 79 1e da 7e f2 c0 22 50 18   H#...}Yy..~.."P.
0030   01 ff 3a b4 00 00 04 01 01 0b 00 34 01 00 81 05   ..:........4....
0040   00 00 00 00 00 10 00 38 02 49 00 44 00 00 00 00   .......8.I.D....
0050   00 09 00 26 04 08 50 00 61 00 72 00 65 00 6e 00   ...&..P.a.r.e.n.
0060   74 00 49 00 44 00 00 00 00 00 09 00 e7 90 01 09   t.I.D...........
0070   04 d0 00 34 04 4e 00 61 00 6d 00 65 00 00 00 00   ...4.N.a.m.e....
0080   00 09 00 e7 a0 0f 09 04 d0 00 34 0e 43 00 61 00   ..........4.C.a.
0090   6c 00 63 00 75 00 6c 00 61 00 74 00 65 00 64 00   l.c.u.l.a.t.e.d.
00a0   50 00 61 00 74 00 68 00 00 00 00 00 00 00 38 07   P.a.t.h.......8.
00b0   52 00 4f 00 57 00 53 00 54 00 41 00 54 00 a4 2b   R.O.W.S.T.A.T..+
00c0   00 02 03 00 64 00 62 00 6f 00 10 00 79 00 41 00   ....d.b.o...y.A.
00d0   63 00 74 00 69 00 76 00 69 00 74 00 79 00 4f 00   c.t.i.v.i.t.y.O.
00e0   75 00 74 00 63 00 6f 00 6d 00 65 00 a5 0f 00 01   u.t.c.o.m.e.....
00f0   01 00 02 01 00 03 01 00 04 01 00 05 00 14 ff 11   ................
0100   00 c1 00 00 00 00 00 00 00 00 00 79 00 00 00 00   ...........y....
0110   ac 00 00 00 01 00 00 00 00 00 00 26 04 04 f3 de   ...........&....
0120   bc 0a ac 04 00 00 01 00 00 00 00 00 00 26 04 04   .............&..
0130   ff ff ff ff fe 00 00 e0 00 00 00 00 00 00 00 00   ................
0140   00                                                .

**Comment by Technus** [comment]
For some reason ReturnValue always has flags?

**Comment by mp911de** [comment]
Can you provide a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem? Ideally a bit of SQL (`CREATE TABLE`, `INSERT INTO`, `SELECT`).

**Comment by Technus** [comment]
Select id from tableName

Literally amy select didnt work for me

**Comment by mp911de** [comment]
I'm not sure, but this might be also an protocol incompatibility. We've tested against SQL Server 14.x and likely SQL Server 12.x uses an earlier protocol version and so there might be something off.

I will be able to investigate on this likely next week or maybe later. Perhaps it's as simple as setting `encryptionSupported` on connection initialization to the right value.

**Comment by Technus** [comment]
Tried both on my db.

**Comment by mp911de** [comment]
I'm able to reproduce the issue using a SQL Server 2014 Express instance.

**Comment by mp911de** [comment]
Thanks for your help. That's fixed now. I'm closing the PR draft #91 in favor of b410ffa.

**Comment by Technus** [comment]
Many thanks.
